name: Publish to GitHub Packages

on:
  workflow_run:
    workflows: ["CI / Build & Release"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Debug - List files
        run: ls -la

      - name: Debug - Check gradle properties
        run: |
          echo "=== gradle.properties ==="
          cat gradle.properties || echo "gradle.properties not found"
          echo "=== build.gradle ==="
          grep -A 20 "publishing" build.gradle || echo "publishing block not found"

      - name: Publish package with debug
        run: |
          ./gradlew publish --info --stacktrace
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify publication
        run: |
          echo "Publication completed. Check GitHub Packages in repository settings."